//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.04 at 12:08:30 AM IST 
//


package com.banu.soapdriverapp.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="drivers" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="nic" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="vehicle_no" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="vehicle_type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="date_of_birth" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="created_by" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="created_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "drivers"
})
@XmlRootElement(name = "GetAllDriversResponse")
public class GetAllDriversResponse {

    protected List<GetAllDriversResponse.Drivers> drivers;

    /**
     * Gets the value of the drivers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the drivers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDrivers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GetAllDriversResponse.Drivers }
     * 
     * 
     */
    public List<GetAllDriversResponse.Drivers> getDrivers() {
        if (drivers == null) {
            drivers = new ArrayList<GetAllDriversResponse.Drivers>();
        }
        return this.drivers;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="nic" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="vehicle_no" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="vehicle_type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="date_of_birth" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="created_by" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="created_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "name",
        "nic",
        "vehicleNo",
        "vehicleType",
        "dateOfBirth",
        "gender",
        "createdBy",
        "createdAt"
    })
    public static class Drivers {

        protected int id;
        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String nic;
        @XmlElement(name = "vehicle_no", required = true)
        protected String vehicleNo;
        @XmlElement(name = "vehicle_type", required = true)
        protected String vehicleType;
        @XmlElement(name = "date_of_birth", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dateOfBirth;
        @XmlElement(required = true)
        protected String gender;
        @XmlElement(name = "created_by", required = true)
        protected String createdBy;
        @XmlElement(name = "created_at", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar createdAt;

        /**
         * Gets the value of the id property.
         * 
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the nic property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNic() {
            return nic;
        }

        /**
         * Sets the value of the nic property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNic(String value) {
            this.nic = value;
        }

        /**
         * Gets the value of the vehicleNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVehicleNo() {
            return vehicleNo;
        }

        /**
         * Sets the value of the vehicleNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVehicleNo(String value) {
            this.vehicleNo = value;
        }

        /**
         * Gets the value of the vehicleType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVehicleType() {
            return vehicleType;
        }

        /**
         * Sets the value of the vehicleType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVehicleType(String value) {
            this.vehicleType = value;
        }

        /**
         * Gets the value of the dateOfBirth property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDateOfBirth() {
            return dateOfBirth;
        }

        /**
         * Sets the value of the dateOfBirth property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDateOfBirth(XMLGregorianCalendar value) {
            this.dateOfBirth = value;
        }

        /**
         * Gets the value of the gender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGender() {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGender(String value) {
            this.gender = value;
        }

        /**
         * Gets the value of the createdBy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCreatedBy() {
            return createdBy;
        }

        /**
         * Sets the value of the createdBy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCreatedBy(String value) {
            this.createdBy = value;
        }

        /**
         * Gets the value of the createdAt property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCreatedAt() {
            return createdAt;
        }

        /**
         * Sets the value of the createdAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCreatedAt(XMLGregorianCalendar value) {
            this.createdAt = value;
        }

    }

}
