//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.03 at 11:01:40 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.banu.com/soapdriverapp/model", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.banu.soapdriverapp.model;
